version: 2
jobs:
  build:
    docker:
      - image: kporras07/docker-drupal-cli:v0.10.7
      - image: nginx:alpine
      - image: kporras07/docker-php:latest
      - image: mailhog/mailhog:v1.0.0
      - image: selenium/standalone-chrome-debug:3.6.0
      - image: mariadb:10.3
        environment:
          MYSQL_DATABASE: drupal
          MYSQL_ROOT_PASSWORD: drupal
    working_directory: /var/www/drupal8cidemo
    steps:
      - run: apt-get update -y
      - run: echo 127.0.0.1 drupal8cidemo.dev | tee -a /etc/hosts
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - composer-cache-{{ checksum "composer.lock" }}
      - run:
          name: Npm and composer install
          command: |
            ln -s .nvm/versions/node/v6.10.1/bin/npm /usr/local/bin/npm
            ln -s .nvm/versions/node/v6.10.1/bin/node /usr/local/bin/node
            npm install
            composer install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: composer-cache-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Configure Nginx
          command: |
            cp ./.circleci/drupal8cidemo /etc/nginx/sites-available/default
      - run:
          name: Build site.
          command: |
            cp ./.circleci/settings.secret.php ./settings/
            chmod 777 -R ./web/sites/default/files
            cd web
            if [ -f /var/www/drupal8cidemo/config/sync/core.extension.yml ] ; then echo 'Install with config' ; /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush si drupal8cidemo -y ; ../vendor/bin/drush config-set "system.site" uuid $SITE_UUID -y ; ../vendor/bin/drush cim -y ; else echo 'Install without config' ; /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush si drupal8cidemo -y ; fi
            cd /var/www/drupal8cidemo
      - run:
          name: Coding Standards Linters
          command: |
            ./node_modules/.bin/gulp phplint
            ./node_modules/.bin/gulp drupalcs
            ./node_modules/.bin/gulp eslint
      - run:
          name: Behat Testing
          command: |
            /etc/init.d/nginx start > nginx.log &
            /etc/init.d/php7.1-fpm start > php7.1-fpm.log &
            ./vendor/bin/behat -p circle

  deploy:
    docker:
      - image: tbfisher/drupal-nginx:php-7.1.x
    working_directory: /var/www/drupal8cidemo
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');" && \
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');"
            mv composer.phar /usr/bin/composer
      - run: composer install
      - run:
          name: Install ahoy
          command: |
            apt-get update -y && apt-get install wget -y
            wget -q https://github.com/ahoy-cli/ahoy/releases/download/2.0.0/ahoy-bin-`uname -s`-amd64 -O /usr/local/bin/ahoy && chmod +x /usr/local/bin/ahoy
      - checkout
      - add_ssh_keys:
          fingerprints:
            # @TODO: Add ssh_key fingerprint here.
            - ""
      - run:
          name: Deploy
          command: |
            # @TODO: Configure git.
            git config --global user.email ""
            git config --global user.name ""
            echo 'Host *' >> /root/.ssh/config
            echo '   StrictHostKeyChecking no' >> /root/.ssh/config
            ahoy site deploy master "Auto deploy triggered from master branch"
      - run:
          name: Install and login terminus
          command: |
            mkdir terminus && cd terminus
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
            ln -s /var/www/drupal8cidemo/terminus/vendor/bin/terminus /usr/bin/terminus
            terminus auth:login --machine-token=$PANTHEON_TOKEN
            terminus drush drupal8cidemo.dev -- si drupal8cidemo --account-pass=admin -y
            terminus drush drupal8cidemo.dev -- config-set "system.site" uuid "$SITE_UUID" -y
            terminus drush drupal8cidemo.dev -- cim -y
            terminus drush drupal8cidemo.dev -- cr
  deploy-test:
    docker:
      - image: tbfisher/drupal-nginx:php-7.1.x
    working_directory: /var/www/drupal8cidemo
    steps:
      - run:
          name: Install and login terminus
          command: |
            echo 'Host *' >> /root/.ssh/config
            echo '   StrictHostKeyChecking no' >> /root/.ssh/config
            mkdir terminus && cd terminus
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
            ln -s /var/www/drupal8cidemo/terminus/vendor/bin/terminus /usr/bin/terminus
            terminus auth:login --machine-token=$PANTHEON_TOKEN
            terminus env:deploy drupal8cidemo.test --note "Autodeploy from Circle" -y
            terminus drush drupal8cidemo.test -- updb -y
            terminus drush drupal8cidemo.test -- cim -y
            terminus drush drupal8cidemo.test -- cr
  deploy-live:
    docker:
      - image: tbfisher/drupal-nginx:php-7.1.x
    working_directory: /var/www/drupal8cidemo
    steps:
      - run:
          name: Install and login terminus
          command: |
            echo 'Host *' >> /root/.ssh/config
            echo '   StrictHostKeyChecking no' >> /root/.ssh/config
            mkdir terminus && cd terminus
            curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
            ln -s /var/www/drupal8cidemo/terminus/vendor/bin/terminus /usr/bin/terminus
            terminus auth:login --machine-token=$PANTHEON_TOKEN
            terminus env:deploy drupal8cidemo.live --note "Autodeploy from Circle" -y
            terminus drush drupal8cidemo.live -- updb -y
            terminus drush drupal8cidemo.live -- cim -y
            terminus drush drupal8cidemo.live -- cr
workflows:
  version: 2
  build-deploys:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-test:
          requires:
            - deploy
      - deploy-live-hold:
          type: approval
          requires:
            - deploy-test
      - deploy-live:
          requires:
            - deploy-live-hold
